package com.example.nextstep.utils

val keywordListMap = mapOf(
    "it" to 1,
    "analysis" to 2,
    "cloud" to 3,
    "management" to 4,
    "aws" to 5,
    "azure" to 6,
    "design" to 7,
    "data" to 8,
    "python" to 9,
    "sql" to 10,
    "troubleshooting" to 11,
    "javascript" to 12,
    "compliance" to 13,
    "windows" to 14,
    "ux" to 15,
    "procurement" to 16,
    "html" to 17,
    "css" to 18,
    "testing" to 19,
    "training" to 20,
    "security" to 21,
    "sales" to 22,
    "governance" to 23,
    "strategy" to 24,
    "project" to 25,
    "ai" to 26,
    "risk" to 27,
    "education" to 28,
    "development" to 29,
    "threat" to 30,
    "cybersecurity" to 31,
    "architecture" to 32,
    "node" to 33,
    "js" to 34,
    "business" to 35,
    "java" to 36,
    "agile" to 37,
    "prototyping" to 38,
    "machine" to 39,
    "learning" to 40,
    "networking" to 41,
    "excel" to 42,
    "cisco" to 43,
    "consulting" to 44,
    "big" to 45,
    "research" to 46,
    "regulations" to 47,
    "coordination" to 48,
    "docker" to 49,
    "jenkins" to 50,
    "database" to 51,
    "tensorflow" to 52,
    "ml" to 53,
    "audit" to 54,
    "manual" to 55,
    "bug" to 56,
    "tracking" to 57,
    "etl" to 58,
    "encryption" to 59,
    "vendor" to 60,
    "user" to 61,
    "blockchain" to 62,
    "solidity" to 63,
    "assessment" to 64,
    "services" to 65,
    "gdpr" to 66,
    "protection" to 67,
    "patterns" to 68,
    "qa" to 69,
    "ios" to 70,
    "android" to 71,
    "mobile" to 72,
    "supply" to 73,
    "chain" to 74,
    "ethics" to 75,
    "analytics" to 76,
    "team" to 77,
    "software" to 78,
    "devops" to 79,
    "detection" to 80,
    "service" to 81,
    "pmp" to 82,
    "r" to 83,
    "linux" to 84,
    "ui" to 85,
    "oracle" to 86,
    "server" to 87,
    "firewall" to 88,
    "react" to 89,
    "requirements" to 90,
    "customer" to 91,
    "devsecops" to 92,
    "ci" to 93,
    "cd" to 94,
    "penetration" to 95,
    "internship" to 96,
    "wan" to 97,
    "active" to 98,
    "directory" to 99,
    "vpn" to 100,
    "change" to 101,
    "desk" to 102,
    "continuity" to 103,
    "disaster" to 104,
    "recovery" to 105,
    "test" to 106,
    "automation" to 107,
    "selenium" to 108,
    "quality" to 109,
    "specialization" to 110,
    "asset" to 111,
    "inventory" to 112,
    "migration" to 113,
    "support" to 114,
    "programming" to 115,
    "computing" to 116,
    "c" to 117,
    "visualization" to 118,
    "network" to 119
)

val keywordList = listOf(
    "it",
    "analysis",
    "cloud",
    "management",
    "aws",
    "azure",
    "design",
    "data",
    "python",
    "sql",
    "troubleshooting",
    "javascript",
    "compliance",
    "windows",
    "ux",
    "procurement",
    "html",
    "css",
    "testing",
    "training",
    "security",
    "sales",
    "governance",
    "strategy",
    "project",
    "ai",
    "risk",
    "education",
    "development",
    "threat",
    "cybersecurity",
    "architecture",
    "node",
    "js",
    "business",
    "java",
    "agile",
    "prototyping",
    "machine",
    "learning",
    "networking",
    "excel",
    "cisco",
    "consulting",
    "big",
    "research",
    "regulations",
    "coordination",
    "docker",
    "jenkins",
    "database",
    "tensorflow",
    "ml",
    "audit",
    "manual",
    "bug",
    "tracking",
    "etl",
    "encryption",
    "vendor",
    "user",
    "blockchain",
    "solidity",
    "assessment",
    "services",
    "gdpr",
    "protection",
    "patterns",
    "qa",
    "ios",
    "android",
    "mobile",
    "supply",
    "chain",
    "ethics",
    "analytics",
    "team",
    "software",
    "devops",
    "detection",
    "service",
    "pmp",
    "r",
    "linux",
    "ui",
    "oracle",
    "server",
    "firewall",
    "react",
    "requirements",
    "customer",
    "devsecops",
    "ci",
    "cd",
    "penetration",
    "internship",
    "wan",
    "active",
    "directory",
    "vpn",
    "change",
    "desk",
    "continuity",
    "disaster",
    "recovery",
    "test",
    "automation",
    "selenium",
    "quality",
    "specialization",
    "asset",
    "inventory",
    "migration",
    "support",
    "programming",
    "computing",
    "c",
    "visualization",
    "network"
)

val jobTitleMap = mapOf(
    "Software Engineer" to 0,
    "Data Analyst" to 1,
    "Network Engineer" to 2,
    "Cloud Architect" to 3,
    "Cybersecurity Analyst" to 4,
    "IT Project Manager" to 5,
    "Data Scientist" to 6,
    "DevOps Engineer" to 7,
    "IT Support Analyst" to 8,
    "UX/UI Designer" to 9,
    "Database Analyst" to 10,
    "UI Developer" to 11,
    "System Administrator" to 12,
    "AI/ML Engineer" to 13,
    "IT Auditor" to 14,
    "Network Security Engineer" to 15,
    "Software Tester" to 16,
    "Cloud Solutions Architect" to 17,
    "IT Consultant" to 18,
    "Front-end Developer" to 19,
    "Business Analyst" to 20,
    "IT Helpdesk Support" to 21,
    "DevSecOps Engineer" to 22,
    "Data Engineer" to 23,
    "IT Trainer" to 24,
    "Cloud Security Engineer" to 25,
    "IT Procurement Specialist" to 26,
    "UX Researcher" to 27,
    "Blockchain Developer" to 28,
    "IT Risk Analyst" to 29,
    "Cloud Support Engineer" to 30,
    "IT Sales Manager" to 31,
    "Data Privacy Officer" to 32,
    "Software Architect" to 33,
    "IT Quality Analyst" to 34,
    "Mobile App Developer" to 35,
    "IT Procurement Manager" to 36,
    "IT Compliance Officer" to 37,
    "Full-stack Developer" to 38,
    "IT Business Analyst" to 39,
    "IT Trainer Assistant" to 40,
    "AI Ethics Consultant" to 41,
    "IT Support Specialist" to 42,
    "Data Analytics Manager" to 43,
    "IT Project Coordinator" to 44,
    "Cloud Solutions Analyst" to 45,
    "IT Governance Manager" to 46,
    "Cybersecurity Engineer" to 47,
    "IT Procurement Analyst" to 48,
    "UX Designer" to 49,
    "IT Change Manager" to 50,
    "IT Service Desk Analyst" to 51,
    "Cloud Security Analyst" to 52,
    "IT Business Continuity Manager" to 53,
    "QA Automation Engineer" to 54,
    "Data Governance Analyst" to 55,
    "IT Trainer Specialist" to 56,
    "Machine Learning Engineer" to 57,
    "IT Asset Manager" to 58,
    "IT Security Consultant" to 59,
    "Data Analyst Intern" to 60,
    "IT Sales Representative" to 61,
    "Cloud Migration Specialist" to 62,
    "IT Procurement Coordinator" to 63,
    "IT Analyst Trainee" to 64,
    "UX Research Assistant" to 65,
    "IT Compliance Specialist" to 66,
    "Software Development Intern" to 67,
    "Network Administrator Trainee" to 68,
    "Cloud Solutions Intern" to 69,
    "Software Developer" to 70,
    "IT Analyst" to 71,
    "Database Administrator" to 72,
    "IT Security Analyst" to 73
)

val jobTitle = listOf(
    "Software Engineer",
    "Data Analyst",
    "Network Engineer",
    "Cloud Architect",
    "Cybersecurity Analyst",
    "IT Project Manager",
    "Data Scientist",
    "DevOps Engineer",
    "IT Support Analyst",
    "UX/UI Designer",
    "Database Analyst",
    "UI Developer",
    "System Administrator",
    "AI/ML Engineer",
    "IT Auditor",
    "Network Security Engineer",
    "Software Tester",
    "Cloud Solutions Architect",
    "IT Consultant",
    "Front-end Developer",
    "Business Analyst",
    "IT Helpdesk Support",
    "DevSecOps Engineer",
    "Data Engineer",
    "IT Trainer",
    "Cloud Security Engineer",
    "IT Procurement Specialist",
    "UX Researcher",
    "Blockchain Developer",
    "IT Risk Analyst",
    "Cloud Support Engineer",
    "IT Sales Manager",
    "Data Privacy Officer",
    "Software Architect",
    "IT Quality Analyst",
    "Mobile App Developer",
    "IT Procurement Manager",
    "IT Compliance Officer",
    "Full-stack Developer",
    "IT Business Analyst",
    "IT Trainer Assistant",
    "AI Ethics Consultant",
    "IT Support Specialist",
    "Data Analytics Manager",
    "IT Project Coordinator",
    "Cloud Solutions Analyst",
    "IT Governance Manager",
    "Cybersecurity Engineer",
    "IT Procurement Analyst",
    "UX Designer",
    "IT Change Manager",
    "IT Service Desk Analyst",
    "Cloud Security Analyst",
    "IT Business Continuity Manager",
    "QA Automation Engineer",
    "Data Governance Analyst",
    "IT Trainer Specialist",
    "Machine Learning Engineer",
    "IT Asset Manager",
    "IT Security Consultant",
    "Data Analyst Intern",
    "IT Sales Representative",
    "Cloud Migration Specialist",
    "IT Procurement Coordinator",
    "IT Analyst Trainee",
    "UX Research Assistant",
    "IT Compliance Specialist",
    "Software Development Intern",
    "Network Administrator Trainee",
    "Cloud Solutions Intern",
    "Software Developer",
    "IT Analyst",
    "Database Administrator",
    "IT Security Analyst"
)